name: slaypay_cc
description: SlayPay Card Customization
version: 1.0.0+0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: ^4.6.1
  flutter_svg: ^0.22.0
  flutter_neumorphic: ^3.2.0
  flutter_staggered_animations: ^1.0.0
  animated_item_picker: ^1.0.4
  syncfusion_flutter_sliders: ^19.4.53
  image_picker: ^0.8.4+10
  auto_size_text_field: ^1.0.1
  focus_widget: ^1.0.5+2
  google_fonts: ^2.3.1
  photo_view: ^0.13.0
  scroll_to_index: ^2.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/card_images/
    - assets/card_images/patterns/


  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand.otf
    - family: BeautifulPeople
      fonts:
        - asset: assets/fonts/BeautifulPeople.ttf
    - family: BeautyMountains
      fonts:
        - asset: assets/fonts/BeautyMountains.ttf
    - family: BiteChocolate
      fonts:
        - asset: assets/fonts/BiteChocolate.ttf
    - family: BlackberryJam
      fonts:
        - asset: assets/fonts/BlackberryJam.ttf
    - family: Tomatoes
      fonts:
        - asset: assets/fonts/Tomatoes.ttf
    - family: BunchBlossoms
      fonts:
        - asset: assets/fonts/BunchBlossoms.ttf
    - family: CinderelaRegular
      fonts:
        - asset: assets/fonts/CinderelaRegular.ttf
    - family: Countryside
      fonts:
        - asset: assets/fonts/Countryside.ttf
    - family: Halimun
      fonts:
        - asset: assets/fonts/Halimun.ttf
    - family: LemonJelly
      fonts:
        - asset: assets/fonts/LemonJelly.ttf
    - family: QuiteMagicalRegular
      fonts:
        - asset: assets/fonts/QuiteMagicalRegular.ttf
    - family: TropicalAsianDemoRegular
      fonts:
        - asset: assets/fonts/TropicalAsianDemoRegular.ttf
    - family: VeganStyle
      fonts:
        - asset: assets/fonts/VeganStyle.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/fonts/MaterialIcons_Regular.ttf

